---
- name: "install erlang, elixir, nodejs"
  homebrew: name="{{ item }}" state="latest"
  with_items:
    - erlang
    - elixir
    - node
- name: "inatall phoenix framework and dependency mix local.hex"
  command: "{{ item }}"
  with_items:
    - "mix local.hex --force"
    - "mix local.rebar --force"
    - "mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force"
